# Generated by Django 3.2.15 on 2022-09-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='pics_product/')),
                ('name', models.CharField(blank=True, max_length=149, null=True)),
                ('points', models.IntegerField(blank=True, max_length=149, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='pics_reward/')),
                ('name', models.CharField(blank=True, max_length=149, null=True)),
                ('value', models.IntegerField(blank=True, max_length=149, null=True)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_checker', to='extended_user.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_profile', to='extended_user.profile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_ventas.reward')),
            ],
        ),
    ]
