# Generated by Django 3.2.15 on 2022-09-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0002_alter_profile_disponible_points'),
        ('control_ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Rewards',
            new_name='Profile_Reward',
        ),
    ]
