# Generated by Django 3.2.15 on 2022-09-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disponible_points',
            field=models.IntegerField(default=0),
        ),
    ]
